### ISSUE TITLE
Extension interferes with http requests made by other extensions

### ISSUE THREAD

**Issue by trym** [Azure/vscode-kubernetes-tools#563]
Having the kubernetes extension enabled breaks certain http requests in other extensions.
Disabling it fixes the issue.

```pre
workbench.main.js:3241 NetworkingError: Cannot set headers after they are sent to the client
	at ClientRequest.setHeader (_http_outgoing.js:471:11)
	at Function.AutoCollectClientRequests.trackRequest (/Users/krijoh/.vscode/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.0.0/node_modules/applicationinsights/AutoCollection/ClientRequests.js:77:33)
	at Object.AutoCollectClientRequests._initialize.https.request (/Users/krijoh/.vscode/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.0.0/node_modules/applicationinsights/AutoCollection/ClientRequests.js:53:47)
	at util.inherit.features.constructor.handleRequest (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/http/node.js:45:23)
	at executeSend (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/event_listeners.js:342:29)
	at Request.SEND (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/event_listeners.js:356:9)
	at Request.callListeners (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
	at Request.emit (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
	at Request.emit (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/request.js:683:14)
	at Request.transition (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/request.js:22:10)
	at AcceptorStateMachine.runTo (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/state_machine.js:14:12)
	at /Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/state_machine.js:26:10
	at Request.<anonymous> (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/request.js:38:9)
	at Request.<anonymous> (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/request.js:685:12)
	at Request.callListeners (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
	at callNextListener (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
	at /Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/event_listeners.js:241:9
	at finish (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/config.js:349:7)
	at /Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/config.js:367:9
	at Credentials.get (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/credentials.js:127:7)
	at getAsyncCredentials (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/config.js:361:24)
	at Config.getCredentials (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/config.js:381:9)
	at Request.SIGN (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/event_listeners.js:212:22)
	at Request.callListeners (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
	at callNextListener (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
	at Request.discoverEndpoint (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/discover_endpoint.js:326:67)
	at Request.callListeners (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
	at Request.emit (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
	at Request.emit (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/request.js:683:14)
	at Request.transition (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/request.js:22:10)
	at AcceptorStateMachine.runTo (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/state_machine.js:14:12)
	at /Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/state_machine.js:26:10
	at Request.<anonymous> (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/request.js:38:9)
	at Request.<anonymous> (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/request.js:685:12)
	at Request.callListeners (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
	at Timeout.callNextListener [as _onTimeout] (/Users/krijoh/.vscode/extensions/skalar.kpd-0.0.1/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
	at ontimeout (timers.js:427:11)
	at tryOnTimeout (timers.js:289:5)
	at listOnTimeout (timers.js:252:5)
	at Timer.processTimers (timers.js:212:10)
```

**Comment by trym** [comment]
From what I can tell, application insights cannot be disabled via configuration, and there is no way of using the helm yaml support without everything else enabled.

**Comment by itowlson** [comment]
Could you provide an example of another extension that we break, and steps for how to reproduce the issue in that extension, please?  We certainly shouldn't be doing anything with global HTTP configuration....

I see Application Insights on that stack trace so this may be something we need to get fixed in the Insights upstream.  In the meantime you could try turning telemetry off (`telemetry.enableTelemetry` config setting) and see if that helps?

**Comment by itowlson** [comment]
Could you also let me know if you have any other extensions installed please?  We configure AI so that it doesn't go through that code path, but reading the module it seems like if _another_ extension is already using Application Insights then we might share its configuration... though in that case I'd expect the other extension to also be triggering this issue...  Thanks!

**Comment by itowlson** [comment]
I can see we are on a very old version of Application Insights so I should update that anyway, and perhaps that might help...

**Comment by trym** [comment]
The extension I'm experiencing this with is yet to be published. It does not use application insights. 

Steps to reproduce:
* generate a new vscode extension
* install the aws-sdk npm package
* from within the extension, upload of a file (stream) to a bucket using S3#upload() - it has to be large enough to trigger multiple parts (>5MiB I think)

Disabling telemetry does not make a difference it seems, but disabling the kubernetes extension entirely, does. Had the Helm YAML support been a separate package, that would be an ok workaround for me -

**Comment by itowlson** [comment]
Thanks @trym - I've reproduced the problem, investigating now.

**Comment by itowlson** [comment]
Test harness exhibits the problem with old telemetry package but not new telemetry package.  If that's the issue then #566 will fix it.  Testing now.

**Comment by itowlson** [comment]
Confirmed my test harness doesn't show the behaviour when k8s extension is built from tip.  I'll publish a release to the store shortly - hopefully it will resolve your more realistic scenario too!

**Comment by itowlson** [comment]
Could you grab the new (1.0.1) version of the extension off the Marketplace please (should auto-update I believe, otherwise update manually), and let us know whether it fixes your problem or not?  Thanks!

**Comment by trym** [comment]
Problem fixed, thanks :)
