### ISSUE TITLE
error (command 'extension.vsKubernetesConfigureFromCluster' not found)

### ISSUE THREAD

**Issue by karlrissland** [Azure/vscode-kubernetes-tools#740]
Issue Type: <b>Bug</b>

Opened visual studio code
Clicked on the Kubernetes Icon on the left
Clicked ... in the clusters group
Selected add existing cluster
---- nothing happened
ctrl-shft-p
used add existing cluster
---- get an alert stating that 'Kubernetes: Add Existing Cluster' resulted ni an error (command 'extension.vsKubernetesConfigureFromCluster' not found)

I removed and reloaded the extension

Same error

![image](https://user-images.githubusercontent.com/9871029/80034947-2dc82c00-84bd-11ea-8d70-ec431661d266.png)

Extension version: 1.1.1
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by karlrissland** [comment]
NOTE: playing around a little more, discovered that the kubernetes element in settings.json was existed and was empty even after uninstalling the extension.  Completely removed the kubernetes entry in the settings file for both the workspace and the user.  Reinstalled the extension and it appears to be working now.

**Comment by itowlson** [comment]
Super weird that an empty config setting could cause this behaviour but thank you for taking the time to investigate and to let us know the outcome!  Glad it's working now!

**Comment by jupacaza** [comment]
> NOTE: playing around a little more, discovered that the kubernetes element in settings.json was existed and was empty even after uninstalling the extension. Completely removed the kubernetes entry in the settings file for both the workspace and the user. Reinstalled the extension and it appears to be working now.

I tried this but did not work. Still can't use the Kubernetes extension.

**Comment by lstocchi** [comment]
@jupacaza sorry to hear that but I really don't know how to help you without any other infos. I'm not able to replicate it. 

Do you see any error/log if you open the developer tools console (Help -> Toggle Developer Tools)? How did you install VSCode? There are ppl who installed it using snap and it gives them issues because of some permission. 

Can you verify you have installed the RedHat's YAML extension?

Have you ever used this extension before? Is it the first time you installed it? 

If you go inside the extensions folder of your vscode you can actually see the extension folder (something like ../.vscode/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.2.0)? Maybe you can try reinstalling all dependencies manually inside that folder `npm install`, sometimes the download doesn't complete successfully.  

Are you trying to use minikube? If not, could you make a test with it and see if it shows in the clusters list? So if it works we can think of a different issue. 

These are all the ideas that came to my mind now. Hope they can give you some help. Let us know if you solve this somehow :)

**Comment by itowlson** [comment]
@jupacaza Can you provide a list of other installed extensions?  Also, can you look in the VS Code Output pane, drop down the channel list near the top right of the pane, and look in the `Log (Extension Host)` channel, and see if there are any messages from around the time you tried to run the command.  Thanks!

**Comment by jupacaza** [comment]
Log (Extension Host):

[2020-06-29 13:25:11.895] [exthost] [info] extension host started
[2020-06-29 13:25:11.931] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-06-29 13:25:11.931] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/debug-auto-launch/dist/extension
[2020-06-29 13:25:11.996] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-06-29 13:25:11.996] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/emmet/dist/extension
[2020-06-29 13:25:12.142] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-06-29 13:25:12.142] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/git/dist/main
[2020-06-29 13:25:12.237] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":true,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"*"}
[2020-06-29 13:25:12.237] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/github-authentication/dist/extension.js
[2020-06-29 13:25:12.285] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-06-29 13:25:12.285] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/merge-conflict/dist/extension
[2020-06-29 13:25:12.316] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":true,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"*"}
[2020-06-29 13:25:12.316] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2020-06-29 13:25:12.345] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-06-29 13:25:12.345] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/search-result/dist/extension.js
[2020-06-29 13:25:12.355] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":true,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"*"}
[2020-06-29 13:25:12.355] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/eamodio.gitlens-10.2.2/dist/extension
[2020-06-29 13:25:12.425] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.azure-account {"startup":true,"extensionId":{"value":"ms-azure-devops.azure-pipelines","_lower":"ms-azure-devops.azure-pipelines"},"activationEvent":"*"}
[2020-06-29 13:25:12.425] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/ms-vscode.azure-account-0.8.11/dist/extension
[2020-06-29 13:25:12.715] [exthost] [info] ExtensionService#_doActivateExtension Okteto.kubernetes-context {"startup":true,"extensionId":{"value":"Okteto.kubernetes-context","_lower":"okteto.kubernetes-context"},"activationEvent":"*"}
[2020-06-29 13:25:12.715] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/okteto.kubernetes-context-0.1.0/dist/extension
[2020-06-29 13:25:13.410] [exthost] [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-azurefunctions {"startup":true,"extensionId":{"value":"ms-azuretools.vscode-azurefunctions","_lower":"ms-azuretools.vscode-azurefunctions"},"activationEvent":"workspaceContains:*/host.json"}
[2020-06-29 13:25:13.410] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/main.js
[2020-06-29 13:25:14.501] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-06-29 13:25:14.501] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/github/dist/extension.js
[2020-06-29 13:25:14.637] [exthost] [info] ExtensionService#_doActivateExtension ms-azure-devops.azure-pipelines {"startup":true,"extensionId":{"value":"ms-azure-devops.azure-pipelines","_lower":"ms-azure-devops.azure-pipelines"},"activationEvent":"*"}
[2020-06-29 13:25:14.637] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/ms-azure-devops.azure-pipelines-1.170.0/out/extension
[2020-06-29 13:25:51.262] [exthost] [info] ExtensionService#_doActivateExtension redhat.vscode-yaml {"startup":false,"extensionId":{"value":"ms-kubernetes-tools.vscode-kubernetes-tools","_lower":"ms-kubernetes-tools.vscode-kubernetes-tools"},"activationEvent":"onView:extension.vsKubernetesExplorer"}
[2020-06-29 13:25:51.262] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/redhat.vscode-yaml-0.8.0/out/src/extension
[2020-06-29 13:25:51.266] [exthost] [error] Activating extension redhat.vscode-yaml failed due to an error:
[2020-06-29 13:25:51.266] [exthost] [error] c:\Users\jucallej\.vscode\extensions\redhat.vscode-yaml-0.8.0\out\src\extension.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              

SyntaxError: Invalid or unexpected token
	at new Script (vm.js:86:7)
	at Module.o._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:396)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:974:268)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:943:114)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:939:443)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:33:115)
	at h._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:944:266)
	at h._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:838:856)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:837:937)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:835:883)
	at e._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:609:859)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:609:537
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:609:525)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:609:594)
	at e.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:607:14)
	at h._activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:836:618)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:846:159
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-06-29 13:25:53.271] [exthost] [info] eager extensions activated


List of installed extensions:
> code --list-extensions
eamodio.gitlens
humao.rest-client
icsharpcode.ilspy-vscode
ms-azure-devops.azure-pipelines
ms-azuretools.vscode-azureappservice
ms-azuretools.vscode-azurefunctions
ms-azuretools.vscode-azureresourcegroups
ms-azuretools.vscode-azurestorage
ms-azuretools.vscode-azurevirtualmachines
ms-azuretools.vscode-cosmosdb
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-kubernetes-tools.vscode-kubernetes-tools
ms-mssql.mssql
ms-python.python
ms-vscode.azure-account
ms-vscode.azurecli
ms-vscode.powershell
ms-vscode.vscode-node-azure-pack
msazurermtools.azurerm-vscode-tools
Okteto.kubernetes-context
redhat.vscode-yaml

**Comment by itowlson** [comment]
Looks like RedHat YAML (which the k8s extension depends on) has an error.

Could you try this please:

* Uninstall the k8s extension
* Uninstall RedHat YAML
* Restart all instances of VS Code
* Reinstall RedHat YAML from the marketplace
* Open a YAML file and confirm no error
* Reinstall k8s extension
* See if you still get the k8s error

Thanks!

**Comment by jupacaza** [comment]
Worked! Thank you!

Logs in case you need them as reference:

> [2020-06-29 14:04:14.421] [exthost] [info] extension host started
[2020-06-29 14:04:14.472] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-06-29 14:04:14.473] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/debug-auto-launch/dist/extension
[2020-06-29 14:04:14.478] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-06-29 14:04:14.478] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/emmet/dist/extension
[2020-06-29 14:04:14.501] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-06-29 14:04:14.501] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/git/dist/main
[2020-06-29 14:04:14.542] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":true,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"*"}
[2020-06-29 14:04:14.542] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/github-authentication/dist/extension.js
[2020-06-29 14:04:14.556] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-06-29 14:04:14.556] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/merge-conflict/dist/extension
[2020-06-29 14:04:14.560] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":true,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"*"}
[2020-06-29 14:04:14.560] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2020-06-29 14:04:14.574] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-06-29 14:04:14.574] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/search-result/dist/extension.js
[2020-06-29 14:04:14.577] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":true,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"*"}
[2020-06-29 14:04:14.577] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/eamodio.gitlens-10.2.2/dist/extension
[2020-06-29 14:04:14.626] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.azure-account {"startup":true,"extensionId":{"value":"ms-azure-devops.azure-pipelines","_lower":"ms-azure-devops.azure-pipelines"},"activationEvent":"*"}
[2020-06-29 14:04:14.626] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/ms-vscode.azure-account-0.8.11/dist/extension
[2020-06-29 14:04:14.795] [exthost] [info] ExtensionService#_doActivateExtension Okteto.kubernetes-context {"startup":true,"extensionId":{"value":"Okteto.kubernetes-context","_lower":"okteto.kubernetes-context"},"activationEvent":"*"}
[2020-06-29 14:04:14.795] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/okteto.kubernetes-context-0.1.0/dist/extension
[2020-06-29 14:04:15.398] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-06-29 14:04:15.398] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/github/dist/extension.js
[2020-06-29 14:04:15.411] [exthost] [info] ExtensionService#_doActivateExtension ms-azure-devops.azure-pipelines {"startup":true,"extensionId":{"value":"ms-azure-devops.azure-pipelines","_lower":"ms-azure-devops.azure-pipelines"},"activationEvent":"*"}
[2020-06-29 14:04:15.411] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/ms-azure-devops.azure-pipelines-1.170.0/out/extension
[2020-06-29 14:04:17.024] [exthost] [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-azurefunctions {"startup":true,"extensionId":{"value":"ms-azuretools.vscode-azurefunctions","_lower":"ms-azuretools.vscode-azurefunctions"},"activationEvent":"workspaceContains:*/host.json"}
[2020-06-29 14:04:17.024] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/main.js
[2020-06-29 14:04:18.206] [exthost] [info] eager extensions activated
[2020-06-29 14:04:49.991] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"extensionId":{"value":"vscode.extension-editing","_lower":"vscode.extension-editing"},"activationEvent":"onLanguage:typescript"}
[2020-06-29 14:04:49.991] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/extension-editing/dist/extension
[2020-06-29 14:04:50.003] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:typescript"}
[2020-06-29 14:04:50.003] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/typescript-language-features/dist/extension
[2020-06-29 14:05:10.793] [exthost] [info] ExtensionService#_doActivateExtension redhat.vscode-yaml {"startup":false,"extensionId":{"value":"redhat.vscode-yaml","_lower":"redhat.vscode-yaml"},"activationEvent":"onLanguage:yaml"}
[2020-06-29 14:05:10.793] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/redhat.vscode-yaml-0.8.0/out/src/extension
[2020-06-29 14:05:10.904] [exthost] [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-docker {"startup":false,"extensionId":{"value":"ms-azuretools.vscode-docker","_lower":"ms-azuretools.vscode-docker"},"activationEvent":"onLanguage:yaml"}
[2020-06-29 14:05:10.904] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/ms-azuretools.vscode-docker-1.3.1/main
[2020-06-29 14:06:27.179] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:json"}
[2020-06-29 14:06:27.179] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/configuration-editing/dist/extension
[2020-06-29 14:06:27.184] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:json"}
[2020-06-29 14:06:27.184] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/json-language-features/client/dist/jsonMain
[2020-06-29 14:06:27.219] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onLanguage:json"}
[2020-06-29 14:06:27.219] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2020-06-29 14:06:27.465] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":false,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"onLanguage:json"}
[2020-06-29 14:06:27.465] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/npm/dist/main
[2020-06-29 14:06:27.475] [exthost] [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime {"startup":false,"extensionId":{"value":"msazurermtools.azurerm-vscode-tools","_lower":"msazurermtools.azurerm-vscode-tools"},"activationEvent":"onLanguage:json"}
[2020-06-29 14:06:27.475] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/extension.js
[2020-06-29 14:06:27.608] [exthost] [info] ExtensionService#_doActivateExtension msazurermtools.azurerm-vscode-tools {"startup":false,"extensionId":{"value":"msazurermtools.azurerm-vscode-tools","_lower":"msazurermtools.azurerm-vscode-tools"},"activationEvent":"onLanguage:json"}
[2020-06-29 14:06:27.608] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.11.0/main
[2020-06-29 14:06:59.080] [exthost] [info] ExtensionService#_doActivateExtension ms-kubernetes-tools.vscode-kubernetes-tools {"startup":false,"extensionId":{"value":"ms-kubernetes-tools.vscode-kubernetes-tools","_lower":"ms-kubernetes-tools.vscode-kubernetes-tools"},"activationEvent":"onLanguage:yaml"}
[2020-06-29 14:06:59.080] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jucallej/.vscode/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.2.1/out/src/extension

**Comment by itowlson** [comment]
Great!  I can only imagine the RH extension got borked on disk, heaven knows how.  Glad it's working now!
